plugins {
    id 'com.android.library'
}

android {
    namespace 'com.emvenhance.core'
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdk rootProject.ext.minSdkVersion
        targetSdk rootProject.ext.targetSdkVersion
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }

    lint {
        abortOnError false
    }
}

dependencies {
    api "io.reactivex.rxjava3:rxjava:$rootProject.rxjava3"
    implementation 'androidx.annotation:annotation:1.7.1'
}
